spring:
  application:
    name: rms

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:rms_db}
    username: ${DB_USER:rms_user}
    password: ${DB_PASSWORD:rms_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

jwt.key: ${JWT_KEY:jP@FxBg)+q#grgA$$ESnfBNnmZrgY%P#Z2I)DMRvGa!W%xpcnFuIDj^MW)LX!!Hg}
jwt.expirationMillis: ${JWT_LIFETIME:3600000}

refresh-tokens:
  length: 64
  max-per-user: 5
  validity-days: 30

springdoc.swagger-ui.path: /swagger-ui.html