name: Build and Deploy

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch:

env:
  REGION: europe-central2
  GAR_REPO: rms-repo
  SERVICE_NAME: rms-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment Variables based on Branch
        run: |
          if [[ "${{ github.ref_name }}" == 'main' ]]; then
            echo "GCP_PROJECT_ID=${{ secrets.PROD_GCP_PROJECT_ID }}" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.PROD_GCP_SA_KEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == 'dev' ]]; then
            echo "GCP_PROJECT_ID=${{ secrets.DEV_GCP_PROJECT_ID }}" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.DEV_GCP_SA_KEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            exit 1
          fi

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.SERVICE_ACCOUNT_KEY }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests
        run: ./mvnw verify

      - name: Docker Auth
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |-
          docker build -t "${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" .
          docker tag "${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" "${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.SERVICE_NAME }}:latest"

      - name: Push Docker Image
        run: |-
          docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.SERVICE_NAME }}:latest"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          project_id: ${{ env.GCP_PROJECT_ID }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          flags: '--port=8080'